### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by deep-diver** [deep-diver/llamaduo#4]
For visibility cc'ing: @sayakpaul 

Tech stack
- Gemma 2B/7B models 
    - Hugging Face(HF) transformers for modeling
    - HF peft for parameter efficient fine-tuning
    - HF text-generation-inference for serving
    - HF Hub for versioning fine-tuned models
    - HF trl for streamlining SFT fine-tuning process

Pipeline
1. (manual) Manually launching the LLM fine-tuning

2. (automate) Evaluating the fine-tuned LLM

3. (conditional) based on the results from the step 2.
    - (automate) if the performance is any better, replace the existing model on the target HF Model Repo
    - (manual) if the performance is bad, run a script to generate synthetic data that look similar to the existing ones
        -  Go back to the step 1

4. (automate) from step 3, if the performance is determined to be good enough, the currently serving model by TGI will be replaced accordingly.
    - we assume TGI is running on somewhere in the cloud like `dstack` or HF Space repo with Hugging Chat.

**Comment by deep-diver** [comment]
Action items

## 0. dataset preparation

- the target dataset is the filtered [no-robots](https://huggingface.co/datasets/HuggingFaceH4/no_robots) dataset with only `Coding` category.
- the `no-robots` dataset comes with train and test splits, so we are going to use the `train` split for fine-tuning and `test` split for evaluating the fine-tuned model.

## 1. fine-tuning script

- this script should look similar to the standard transformers + peft + trl usage (guide [link1](https://huggingface.co/blog/gemma-peft), [link2](https://huggingface.co/blog/personal-copilot)).
- additionally, we could add an option to run fine-tuning process on Vertex AI ([guide link](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_gemma_peft_finetuning_hf.ipynb)).
- (optional) running the script on `dstack`

## 2. evaluation script

- this script leverages service LLM (Gemini, ChatGPT, ...) to evaluate fine-tuned model on the `test` split.
- each item in the `test` split contains `messages` which is basically a pair of user and assistant's contents. 
    - this script let the fine-tuned model generate output of each item.
    - then, ask to service LLM how the generated output is similar to the recorded output/answer in 1-10 scale score.
    - aggregate scores on all items, then calculate the average score.
- this script decides if the average score is any better
    - than a given threshold (baseline)
    - than the score recorded from the previous model
- if yes, this script drops the following outputs (optionally, direct pushing to HF Model repo)
    - model checkpoint 
    - evaluation results (average score, score on individual items)
    - (TBD) how to push the model to a HF Model repo should be discussed in detail

## 3. Synthetic data generation script

- this script leverages service LLM (Gemini, ChatGPT, ...) to generate synthetic data and add it to the existing `train` split. This script shouldn't look into the `test` split at all, but generate similar data by referring to the `train` split.

## 4. Deployment script

- this script serves the fine-tuned model on {local, cloud} environment with TGI framework.
  - Our primary target cloud environments are HF Space Repo with Hugging Chat template and [dstack](https://dstack.ai/).
- if there is already being served TGI instance, this script will terminate it and replace with the new one (new model)

## 5. Hooking up all scripts for automation

- provide `main.py` script to run things in one place
- provide GitHub Action to control things within GitHub repo

**Comment by sayakpaul** [comment]
Will start with Step 1.

**Comment by deep-diver** [comment]
@sayakpaul not step 0 but step 1, right?

**Comment by sayakpaul** [comment]
I believe you should be able to indendepently work on Step 2? @deep-diver

**Comment by deep-diver** [comment]
@sayakpaul that is correct!

**Comment by sayakpaul** [comment]
> @sayakpaul not step 0 but step 1, right?

Step 0 will be coupled with Step 1.

**Comment by deep-diver** [comment]
Cool! Let's do this

**Comment by sayakpaul** [comment]
Dataset created: https://huggingface.co/datasets/sayakpaul/no_robots_only_coding

```python
from datasets import load_dataset 

dataset = load_dataset("HuggingFaceH4/no_robots")
dataset["train_sft"] = dataset["train_sft"].filter(lambda example: example["category"] == "Coding")
dataset["test_sft"] = dataset["test_sft"].filter(lambda example: example["category"] == "Coding")

dataset.push_to_hub("no_robots_only_coding")

```

Going to spin up an experiment now.

**Comment by sayakpaul** [comment]
Used the following config to start the training run with https://github.com/huggingface/alignment-handbook:

```yaml
# Model arguments
model_name_or_path: google/gemma-7b
model_revision: main
tokenizer_name_or_path: philschmid/gemma-tokenizer-chatml # Custom tokenizer with <|im_start|> and <|im_end|> tokens
torch_dtype: bfloat16
use_flash_attention_2: true

# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
dataset_mixer:
  sayakpaul/no_robots_only_coding: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: gemma-2b-sft-qlora-no-robots
hub_strategy: every_save
learning_rate: 2.0e-04
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: data/gemma-2b-sft-qlora-no-robots
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 4
push_to_hub: true
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
```

And then ran (from the root of https://github.com/huggingface/alignment-handbook):

```bash
ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/multi_gpu.yaml scripts/run_sft.py recipes/zephyr-7b-gemma/sft/config_qlora.yaml
```

Model: https://huggingface.co/sayakpaul/gemma-2b-sft-qlora-no-robots/

It's incorrectly named. Should have been 7b.
